language: java

git:
  depth: false

cache:
  directories:
  - "$HOME/.m2"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=silentsoft_acmicpc-maven-plugin

addons:
  sonarcloud:
    organization: "silentsoft"
    token:
      secure: "Tq3ITzEX1ZRPfCoL6a+cg2ZRv07JpntyH9Jhmr8zjCHvMw/6IhK8tx6+w0kAx9ra19MyeeqsjiV8tJ69mCytLCutUncGS5irdwl+r6SLd0XfJS6ZPiLM+zsxvTX3PgDXlxdu43uPSNDql4t2fer5F5MG+m9mK/CInTy195wehzoL9g+Eun9sz2sWYSMU5rOb0EYtoj2Ypp7zPPyP9tzOEulFbnK+B2JMJ0M/izxcc7g9cNIqfMkgXdiYSxA7a+KPbQBOFUoPKyHEoEygSpvE4I8Y3W1ymksZdFSIX4jWJvdQylODLZpvwcjjVHlBFr4abrgxrWlmUPdfbX6wLD+IvX0ZCQoM+qG9jmJMfFJawyxN/NGjp1XXX+2UtmzyUrAbJMymk8sFUtcHijTzRjeptmFYS+CALDX6UPHHer7y0zVDxzs1Xs/zWFRjV6JDaEyY8B9PC0gopwrSIIvnC/cuHNKB7ORfUiZU3oIKEoU8M9JMUJXzrHlAy5zcwBkt4lsU+EXtlvjUNRHHtJ2pEZ3Pdt5P28slN/0ZCFHcsAGQxO3cKc1RrHByNG7Ugc8uXlKTz7Ta4Ro12K6+hQ0KcrjIMWdJIqdsZ8ySomCOdDx8Q+fcS9rmxBjuVRiwKgYKt1nomd0wvCI1i5M+CtqvQ5MCSCcjF+JBojTc0mL82RTLm4U="

notifications:
  slack:
    rooms:
      secure: "GYdqMIE/hTH4SosUyfIVRmmqSJRfWLdzTVDeLgjKrNbaW/sCJzwVrWypt68OHe/t91z8ykTgYwWbu0zlYXbhiFgu/qF8YQ2rG6vWeylGEtK5hTt8ZXSPTWpHNG5hrkUZuV51FrCGKxKlloe5oaoooBxcnzkxJ87ab0WnhEBcG+G/3AS/l9PkflB0RrXyiPPfFgxtqUBOo7dfPLmxUMRrBX6J85QaBeQGUJkeGyO5Y0IZVIs9L8/ysJSNJD+QXgq2m98O8xn0eadfuuTUtInB/+hNZks9dStgfUwveNDL/qHJjUwci7m+z7o0ulslmpcGFHGn+Mq2oF7XDxC9Y5aWWdy5G9zp3PM79xaNdzmkCoHd31HCY8aVyyhF+xa9JKmk6A7vxsPG2ojCPR+e8iDjDRUlm8e7ujxt+dw2cjD5PPHuXBjs4DSFHlZ/Yio4t0Mb6mtmPdUmy//HUg3iL5IJZW7/jneI6ktOiGXA3JATcpm7GEc00WxCcGtMPWZ/eA6TMarVww6RdIhaocH/ZX2sm4V1ZCtD6LhKMK9JFexejLsoFqxFJh7hLawyw+6BZmX6FtCNdjGbRnZNmj9RjjRatba8AyeByqFvaAC+yIeIvvpfR7cp/S0VjEzlD6qBZEjd1qMrD3PdMeeYuAkYdZ0sXFXZaBeOry7ALK7cI4zy2y4="
