language: java

git:
  depth: false

cache:
  directories:
  - "$HOME/.m2"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=silentsoft_acmicpc-maven-plugin

addons:
  sonarcloud:
    organization: "silentsoft"
    token:
      secure: "Tq3ITzEX1ZRPfCoL6a+cg2ZRv07JpntyH9Jhmr8zjCHvMw/6IhK8tx6+w0kAx9ra19MyeeqsjiV8tJ69mCytLCutUncGS5irdwl+r6SLd0XfJS6ZPiLM+zsxvTX3PgDXlxdu43uPSNDql4t2fer5F5MG+m9mK/CInTy195wehzoL9g+Eun9sz2sWYSMU5rOb0EYtoj2Ypp7zPPyP9tzOEulFbnK+B2JMJ0M/izxcc7g9cNIqfMkgXdiYSxA7a+KPbQBOFUoPKyHEoEygSpvE4I8Y3W1ymksZdFSIX4jWJvdQylODLZpvwcjjVHlBFr4abrgxrWlmUPdfbX6wLD+IvX0ZCQoM+qG9jmJMfFJawyxN/NGjp1XXX+2UtmzyUrAbJMymk8sFUtcHijTzRjeptmFYS+CALDX6UPHHer7y0zVDxzs1Xs/zWFRjV6JDaEyY8B9PC0gopwrSIIvnC/cuHNKB7ORfUiZU3oIKEoU8M9JMUJXzrHlAy5zcwBkt4lsU+EXtlvjUNRHHtJ2pEZ3Pdt5P28slN/0ZCFHcsAGQxO3cKc1RrHByNG7Ugc8uXlKTz7Ta4Ro12K6+hQ0KcrjIMWdJIqdsZ8ySomCOdDx8Q+fcS9rmxBjuVRiwKgYKt1nomd0wvCI1i5M+CtqvQ5MCSCcjF+JBojTc0mL82RTLm4U="

notifications:
  slack:
    rooms:
      secure: "b1tOKD0/luxz+cLQ1CDa38o2H/oHWKX1bHIoaDIqPtEDkKWd5bA2LqyiYbDVdMMj5z7UpWoiYevZBeWewu/sMTLUogrqTaEVz1Z/fjLXMIe+EePIXi7cAknTh2xMrTcMnofMoSoqAFCLY6E+3hU5YLDQQB34bb2QoqwIMwrh2PObe2ILKZNSYDdvfYWRbruIj6yBPdfeZbJAfHvcsD9+ia2CXu0uHq/K9KqzcHZHI3XWB/TxH+A2H8wnOcYCGz1/ZUOpNrgKOAFur5xorPDg/NRJw/8CexXV3fkd5jDvzjVuCmlD/t9ZJYKDYIuBKlXOouADN9n8k1zzFeFsNAkH4djyrP37v9bhBHVb4eMavLp3IjoahOPdSVvblbThCLfE+Bd2L5jNP4Psb9qzKLC5dvzwIKwpkqIWroFvOTu3cOJiNhGMsaLnwWhXdye5AZuhA3l7SgozEZ6kLqLF2R/SHQUAVQ4rOOo2MxKEST2mOpV7fmfIT00s6B8cxt2RYo/wTINu0g9vlU3vALiJOeDQyDuyEu5vsLgmYDvlAwfMiMGZnR5xzBmaGbqgqLoUIER7X1dz6FtCBHTriCfjwXRvXFB43egBjQwbdmtz96JUZWmaJOO2ZNDTMxoBi+rOzs37pB3uJkJeCE9CEPjAr3WxLTFQfb2WMfHMKV+1QmKh+l8="
